"""Initial migration.

Revision ID: 709a62d3851d
Revises: 
Create Date: 2022-11-21 14:56:13.711931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '709a62d3851d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['contenido'])
    op.create_unique_constraint(None, 'post', ['contenido_breve'])
    op.create_unique_constraint(None, 'post', ['titulo'])
    op.create_unique_constraint(None, 'post', ['estado'])
    op.create_unique_constraint(None, 'post', ['fecha_creacion'])
    op.alter_column('rol', 'id',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='llave primaria',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('rol', 'rol_nombre',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='nombre del rol',
               existing_nullable=False)
    op.create_unique_constraint(None, 'rol', ['rol_nombre'])
    op.alter_column('usuario', 'id',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='llave primaria',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuario', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='nombre del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'apellido',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='apellido del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='nombre de usuario o identificador',
               existing_nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='direccion de correo electronico del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'password',
               existing_type=mysql.VARCHAR(length=60),
               comment=None,
               existing_comment='contraseña del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='0 = inactivo - 1 = activo',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('usuario', 'fecha_creacion',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='fecha de creación del usuario',
               existing_nullable=False)
    op.create_unique_constraint(None, 'usuario', ['password'])
    op.create_unique_constraint(None, 'usuario', ['nombre'])
    op.create_unique_constraint(None, 'usuario', ['apellido'])
    op.create_unique_constraint(None, 'usuario', ['username'])
    op.create_unique_constraint(None, 'usuario', ['email'])
    op.alter_column('usuario_rol', 'id',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='llave primaria',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuario_rol', 'usuario_id',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='id del usuario',
               existing_nullable=False)
    op.alter_column('usuario_rol', 'rol_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=True,
               comment=None,
               existing_comment='id del rol del usuario')
    op.create_unique_constraint(None, 'usuario_rol', ['usuario_id'])
    op.drop_constraint('usuario_rol_ibfk_1', 'usuario_rol', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('usuario_rol_ibfk_1', 'usuario_rol', 'usuario', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'usuario_rol', type_='unique')
    op.alter_column('usuario_rol', 'rol_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=False,
               comment='id del rol del usuario')
    op.alter_column('usuario_rol', 'usuario_id',
               existing_type=mysql.INTEGER(display_width=10),
               comment='id del usuario',
               existing_nullable=False)
    op.alter_column('usuario_rol', 'id',
               existing_type=mysql.INTEGER(display_width=10),
               comment='llave primaria',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.alter_column('usuario', 'fecha_creacion',
               existing_type=mysql.VARCHAR(length=50),
               comment='fecha de creación del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               comment='0 = inactivo - 1 = activo',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('usuario', 'password',
               existing_type=mysql.VARCHAR(length=60),
               comment='contraseña del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=mysql.VARCHAR(length=255),
               comment='direccion de correo electronico del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='nombre de usuario o identificador',
               existing_nullable=False)
    op.alter_column('usuario', 'apellido',
               existing_type=mysql.VARCHAR(length=50),
               comment='apellido del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               comment='nombre del usuario',
               existing_nullable=False)
    op.alter_column('usuario', 'id',
               existing_type=mysql.INTEGER(display_width=10),
               comment='llave primaria',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'rol', type_='unique')
    op.alter_column('rol', 'rol_nombre',
               existing_type=mysql.VARCHAR(length=255),
               comment='nombre del rol',
               existing_nullable=False)
    op.alter_column('rol', 'id',
               existing_type=mysql.INTEGER(display_width=10),
               comment='llave primaria',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
